# This template merge config file lists:
#
# - name: name of template stuff
# - patterns: strings to do text substitution on
# - rev_id: a sequential revision id of the template repo (manually maintained for now)
# - required: a full list of all files always merged
# - optional: a full list of all files merged when the --optional flag is used with `gut template`
# - ignored: never used in merging, only when populating new repos

name = "Keyboard Template"
patterns = ["wac", "wac", "Wasco-Wishram", "LGPLv3"]
rev_id = 24
required = [".gitignore",
            ".github/workflows/docsygen.yml",
            ".taskcluster.yml",
            "Makefile.am",
            "autogen.sh",
            "configure.ac",
            "docs/_config.yml",
            "docs/_includes/toc.html",
            "docs/_layouts/default.html",
            "docs/assets/css/style.scss"]

optional = [".github/workflows/build.yml",
            "AUTHORS",
            "README.md",
            "wac.kbdgen/layouts/wac.yaml",
            "wac.kbdgen/layouts/en.yaml",
            "wac.kbdgen/project.yaml",
            "wac.kbdgen/resources/mac/background.png",
            "wac.kbdgen/resources/mac/icon.wac.png",
            "wac.kbdgen/resources/mac/readme.html",
            "wac.kbdgen/targets/android.yaml",
            "wac.kbdgen/targets/ios.yaml",
            "wac.kbdgen/targets/mac.yaml",
            "wac.kbdgen/targets/win.yaml",
            "docs/index.md",
            "docs/layout.md"]

ignored  = ["LICENSE"]
